require 'src/util'
suit = require 'lib/suit'
Class = require 'lib/class'
Timer = require 'lib/knife/timer'

require 'src/constants'
require 'src/states/BaseState'
require 'src/states/StateMachine'
require 'src/states/MainMenuState'
require 'src/states/PlayState'
require 'src/states/DisplayCharState'
require 'src/states/QuizState'
require 'src/states/GameOverState'